modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "createtinkeredweapons"
version = "${version}"
displayName = "Create: Tinkered Weapons"
authors = "RidoPipolop"
description = '''
Adds some unique weapons for both variaty and mobility!
'''
logoFile = "icon.png"

[[dependencies.createtinkeredweapons]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtinkeredweapons]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtinkeredweapons]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"